# Daten einlesen

In [ ]:
import numpy as np
import scipy
from matplotlib import pyplot as plt 
import pygame

pygame 2.6.1 (SDL 2.28.4, Python 3.12.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


/home/tim/miniconda3/envs/Opt1/lib/python3.12/site-packages/pygame/pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


In [6]:
dat_mat = scipy.io.loadmat("TrafficDataset/sequence_data1-1_2.mat")
dat_mat.keys()

dict_keys(['__header__', '__version__', '__globals__', 'sequences'])

## repackage data

In [8]:
data_array = np.array(dat_mat["sequences"])
data = []
for part in data_array:
    data.append(part[0][0][0][0])

In [9]:
data

[array([[24.77925585, 28.12730199, 32.0073716 , 35.92546024, 39.19955003],
        [42.85367035, 47.48185611, 50.58399868, 54.90623485, 57.92641874],
        [60.92779019, 64.6900691 , 67.19027318, 70.24255403, 74.05892331]]),
 array([[51.15375275, 56.90807466, 61.63638957, 66.56278159, 71.83926539],
        [61.50266465, 64.50889574, 67.67516339, 71.81155419, 76.5100543 ],
        [63.44997437, 66.63222914, 71.23864806, 75.95713313, 80.03960365]]),
 array([[35.88146118, 40.94760944, 46.89583652, 51.78206315, 56.32432374],
        [44.48773157, 48.39189475, 51.82406349, 56.55233861, 62.63475117],
        [67.19229719, 71.08265443, 73.80493056, 76.68324537, 79.50157596]]),
 array([[10.67433763, 12.74634334, 14.82035135, 17.89836825, 20.38638611],
        [30.26506941, 34.95116597, 39.52528725, 43.68742498, 48.39361876],
        [61.40465781, 65.09494376, 69.96537373, 75.37592642, 79.3463857 ]]),
 array([[56.57205101, 60.3302939 , 64.39060532],
        [72.61677548, 76.32716579, 80.29762

Nur 3 orts-koordinaten, keine zeit komponente

In [6]:
import h5py# mit h5py
with h5py.File('sequence_data1-1_1.mat', 'r') as f:
    data = f['sequences'][:]

OSError: Unable to synchronously open file (file signature not found)

Will nicht funktionieren

In [71]:
from mat4py import loadmat

data = loadmat('sequence_data1-1_1.mat')
data["sequences"][2]

[{'Xarr': [[2.7333870214228604,
    7.903389478164454,
    13.903402095880141,
    18.65342470966774,
    24.63347589178313,
    29.643543786864086],
   [24.601255140716756,
    30.821354526237435,
    37.585509490772104,
    42.823671644279,
    48.24589489492888,
    53.878179294034865],
   [57.93441824708709,
    64.33488214219652,
    68.2252128980101,
    75.3759264227799,
    80.62158589363108,
    85.86724536448186]],
  'Tarr': [72.44, 72.64, 72.84, 73.04, 73.24000000000001, 73.44]}]

Dies kann durchaus richtig sein... \
Tarr - Zeit-Komponente\
Xarr - Orts-Komonente 


In [ ]:
# Kosten funktional
def J (x, tau, x_data):
    result = 0
    for i in range(len(x)):
        tau * np.abs(x[i] - x_data[i])**2
    return result

In [29]:
# Den mittlwert von J jederzeit ausgeben können:
class J_mittel():
    __val = 0
    __n = 0
    def set_val(self, x):
        self.__val = x
        return
    def set_n(self, x):
        self.__n = x
        return
    
    def get_val(self):
        return self.__val
    def get_n(self):
        return self.__n
    
    def get_res(self):
        return self.__val/self.__n

    def __init__(self, x):
        self.__val = x
        self.__n = 1
        return
    
    def add(self, x):
        self.__val += x
        self.__n += 1
        return

J = J_mittel(0)
for i in range(1, 11):
    J.add(i)

J.get_res()

5.0

In [ ]:
import numpy as np
import scipy
from matplotlib import pyplot as plt
import pygame

# Kosten funktional
def J (x, dt, x_data):
    result = 0
    for i in range(len(x)):
        result += dt * np.abs(x[i] - x_data[i])**2
    return result

def f (d, v_max, model = "log"):
    if model == "log":
        return v_max * np.log(d)
    else: # lin
        return v_max * (1 - 1/d)
    
# Den mittlwert von J jederzeit ausgeben können:
class J_mittel():
    __val = 0
    __n = 0
    def set_val(self, x):
        self.__val = x
        return
    def set_n(self, x):
        self.__n = x
        return
    
    def get_val(self):
        return self.__val
    def get_n(self):
        return self.__n
    
    def get_res(self):
        return self.__val/self.__n

    def __init__(self, x):
        self.__val = x
        self.__n = 1
        return
    
    def add(self, x):
        self.__val += x
        self.__n += 1
        return

def d(x, max_W = 2000, loop = True): # Abstandsfunktion, damit immer des nächste auto VOR dem derzeitig betrachteten auto berücksichtigt wird
    d = np.ones_like(x) * 10**10 # anfangs distanz auf sehr groß setzen
    for i in range(len(x)):
        for j in range(len(x)):
            if i == j:
                continue
            else:
                d[i] = x[j]-x[i] if d[i] > x[j]-x[i] and x[j]-x[i] > 0 else d[i]
            if loop and i == len(x)-1: # abnhängig von der breite der anzeige wird nun der abstand zu den anderen autos überprüft
                d[i] = x[j]-((x[i]-max_W)) if d[i] > x[j]-(x[i]-max_W) and x[j]-(x[i]-max_W) > 0 else d[i]
    return d

def single_step(x, v_max, L, dt, model, max_W):
    N = len(x) # Number of initial values == number of vehicles in traffic
    dx = np.zeros(N) # momente initialisieren
    # Leader
    # dx[-1] = v_max
    dist = d(x, max_W)
    for i in range(N):
            
            dx[i] = f(dist[i], v_max, model)
        
    return x + dt * dx, dx

def simulation_screen(x0, v_max, L, dt, model):
    pygame.init()
    W, H = 1500, 200
    screen = pygame.display.set_mode((W, H))
    clock = pygame.time.Clock()
    scale = 10     # skaliert Meter → Pixel
    running = True
    x = np.array(x0, dtype=float)
    while running:
        clock.tick(60) # 60 FPS
        
        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False             # Stop when closed
        
        x, v = single_step(x, v_max, L, dt, model, max_W = W)

        screen.fill((30, 30, 30))

        for i in range(len(x)):
            px = int(x[i]*scale)% W # start again from the beginning of the screen if done with the lap
            py = H // 2 # bewegt sich auf der hälfter der screen höhe
            if i == len(x)-1:
                pygame.draw.circle(screen, (255, 200, 100), (px, py), 8) #cars
            else:
                pygame.draw.circle(screen, (100, 200, 255), (px, py), 8) #cars

            #vx = int(v[i] *0.4) # 0.4 skarilerungs faktor für weniger clutter
            #pygame.draw.line(screen, (255, 160, 60), (py, py), (px+vx, py), 3)  #geschwindigkeits indikator linie
            # Geschwindigkeitspfeil
            vx = int(v[i] * 2)     # skaliert für Anzeige
            pygame.draw.line(screen, (255, 160, 60), (px, py), (px + vx, py), 3)

        pygame.display.flip() # display and render 
    pygame.quit()

pygame 2.6.1 (SDL 2.28.4, Python 3.12.12)
Hello from the pygame community. https://www.pygame.org/contribute.html


/home/tim/miniconda3/envs/Opt1/lib/python3.12/site-packages/pygame/pkgdata.py:25: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  from pkg_resources import resource_stream, resource_exists


In [ ]:
# Parameter
N = 4 # Anzahl autos
FPS = 60
scale_m_zu_px = 10
v_kmh = 100
v_max = v_kmh * scale_m_zu_px / FPS * 1000/3600 # km/h -> m/s
Sicherheitsabstand_m = 50 
L =  Sicherheitsabstand_m * scale_m_zu_px
x0 = np.arange(100, 100+40*N, step=40)      # Startpositionen

print((v_max, L, x0))
simulation_screen(x0, v_max, L, dt=1/FPS, model="log")


In [18]:
from mat4py import loadmat

data = loadmat('sequence_data1-1_1.mat')["sequences"][:]
data[0]

[{'Xarr': [[47.39131045666992, 53.82017733698899, 60.3346047963812],
   [51.39004618507265, 55.5442699154838, 60.39859453202452],
   [71.53057023567337, 77.25613793806153, 82.38676944064528]],
  'Tarr': [14.240000000000002, 14.440000000000001, 14.64]}]

In [27]:
test = data[0]
test[0].get("Xarr"), test[0].get("Tarr"), [i[0] for i in test[0].get("Xarr")]

([[47.39131045666992, 53.82017733698899, 60.3346047963812],
  [51.39004618507265, 55.5442699154838, 60.39859453202452],
  [71.53057023567337, 77.25613793806153, 82.38676944064528]],
 [14.240000000000002, 14.440000000000001, 14.64],
 [47.39131045666992, 51.39004618507265, 71.53057023567337])

In [ ]:
def get_data_stepi(data, i):
    x, y, t, Delta_t = [], [], [], []
    # x, je 3er vektor mit Ortskoordianten, bei Zeit t
    # y, je 3er vektor mit Ortskoordinaten, bei Zeit t + dt
    # t, je einzelne Einträge der Zeit t
    # dt, Zeitschritgröße an Ort x und Zeit t
    for arr in data:
        if i <= len(arr[0].get("Tarr")) - 2:
            x.append([part[i] for part in arr[0].get("Xarr")])
            y.append([part[i+1] for part in arr[0].get("Xarr")])
            t.append(arr[0].get("Tarr")[i])
            dt.append(arr[0].get("Tarr")[i+1] - arr[0].get("Tarr")[i])
        else:
            continue # nicht notwndig, nur der anschaulichkeits halbar
    if x == []:
        print(f"Kein {i}-ter step in daten enthalten")
        return None, None, None, None
    x,y,t,dt = np.array(x), np.array(y), np.array(t), np.array(dt)
    return x,y,t,dt
    
x,y,t,dt = get_data_stepi(data, 4)
x,y,t,dt

(array([[61.56970303, 68.67528654, 92.25823097],
        [24.63347589, 48.24589489, 80.62158589],
        [60.09456424, 63.96240975, 81.51066381],
        [55.41727572, 60.3924182 , 68.99733745]]),
 array([[66.98510131, 73.63573996, 97.64116926],
        [29.64354379, 53.87817929, 85.86724536],
        [63.64482752, 72.65327229, 87.35347528],
        [61.01066274, 66.89786863, 76.80315977]]),
 array([ 24.44,  73.24, 263.44, 326.04]),
 array([0.2, 0.2, 0.2, 0.2]))

Funktioniert wie gewollt

In [ ]:
# Test umsortieren und wieder rückgängig machen

test = np.random.randint(0, 10,(10, 3))
order = np.argsort(test[:, 0])
new_x = test[order]
reodererd = new_x[np.argsort(order)]
test, new_x, reodererd == test

(array([[9, 6, 8],
        [8, 7, 9],
        [5, 0, 4],
        [4, 9, 5],
        [9, 7, 9],
        [7, 2, 5],
        [0, 3, 7],
        [5, 5, 7],
        [3, 3, 4],
        [6, 3, 5]]),
 array([[0, 3, 7],
        [3, 3, 4],
        [4, 9, 5],
        [5, 0, 4],
        [5, 5, 7],
        [6, 3, 5],
        [7, 2, 5],
        [8, 7, 9],
        [9, 6, 8],
        [9, 7, 9]]),
 array([[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]))

In [ ]:
# Neue Abstandsfunktion
def d(x:np.ndarray): # Abstandsfunktion
    d = np.ones_like(x) * np.inf # anfangs distanz auf sehr groß setzen
    order_mask = np.argsort(x[:, 0]) # nach i-ter achse sortieren, hier x achse -> 0
    x_ordered = x[order_mask]
    for i, x_i in enumerate(x_ordered):
        for j, x_j in enumerate(x_ordered[i:]):
            d = np.linalg.norm(x_j - x_i, axis=1)
    return d

d(x)

array([[1.e+10, 1.e+10, 1.e+10]])

In [ ]:
# Kosten funktional
def J (x, dt, x_data):
    result = 0
    for i in range(len(x)):
        dt * np.abs(x[i] - x_data[i])**2
    return result

def f (d, v_max, model = "log"):
    if model == "log":
        return v_max * np.log(d)
    else: # lin
        return v_max * (1 - 1/d)
    
# Den mittlwert von J jederzeit ausgeben können:
class J_mittel():
    __val = 0
    __n = 0
    def set_val(self, x):
        self.__val = x
        return
    def set_n(self, x):
        self.__n = x
        return
    
    def get_val(self):
        return self.__val
    def get_n(self):
        return self.__n
    
    def get_res(self):
        return self.__val/self.__n

    def __init__(self, x):
        self.__val = x
        self.__n = 1
        return
    
    def add(self, x):
        self.__val += x
        self.__n += 1
        return
    

def single_step(x, v_max, L, dt, model, max_W):
    N = len(x) # Number of initial values == number of vehicles in traffic
    dx = np.zeros(N) # momente initialisieren
    # Leader
    # dx[-1] = v_max
    dist = d(x)
    for i in range(N):
            
            dx[i] = f(dist[i], v_max, model)
        
    return x + dt * dx, dx

# ---- obriges als referenz

def Kosten_step(f, J, x:np.ndarray, ysoll:np.ndarray, t:np.ndarray, dt:np.ndarray, h:float, v_max:float, L:float, model:str = "log"):
    y = single_step(x, v_max, L, dt, model, max_W)
    
    return J(y, dt, ysoll)